name: Flutter Android Release

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: 
        actions/checkout@v3

      -uses: 
        actions/setup-java@v2
        with:
          java-version: 1.8
          cache: 'gradle'

      -uses: 
        subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: 'stable'
          cache: true

      -name: Get Flutter version
        run: flutter --version

      -name: Get Dart version
        run: flutter --version
      
      -name: Flutter doctor
        run: flutter doctor -v
      
      -name: Flutter build
        run: flutter build apk --release
      
      -name: Create release
        uses: 
        ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.WORKFLOW_TOKEN }}
          tag: ${{ github.sha }}
          name: ${{ github.sha }}
          body: ${{ github.sha }}